# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Self-Hosted

variables:
  - group: "Battleships Terraform Secrets"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)/BattleShip_Site'

- bash: |
    terraform init \
    -backend-config="storage_account_name=$tf-storage-account-name" \
    -backend-config="container_name=$tf-container-name" \
    -backend-config="key=$tf-key" \
    -backend-config="resource_group_name=$tf-resource-group-name"

#publish code to resources created by terraform