# Variable Group 'Battleships Terraform Secrets' was defined in the Variables tab
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - BattleShip_Site/build/terraform
resources:
  repositories:
  - repository: self
    type: git
    ref: main

#import variable from azure keyvault
variables:
  - group: "Battleships Terraform Secrets"

jobs:
- job: Job_1
  displayName: Terraform Plan
  pool:
    name: Self-Hosted
  steps:
  - checkout: self
    clean: true
#  - task: TerraformInstaller@0
 #   displayName: Install Terraform 1.1.7
  #  inputs:
   #   terraformVersion: 1.1.7
  - task: CmdLine@2
    displayName: Terraform Init
    inputs:
      script: terraform init -backend-config="access_key=$(tf-key)"
      workingDirectory: BattleShip_Site/build/terraform
  - task: CmdLine@2
    displayName: Terraform Validate
    inputs:
      script: terraform validate
      workingDirectory: BattleShip_Site/build/terraform
  - task: CmdLine@2
    displayName: Terraform Plan
    inputs:
      script: >
        terraform plan -input=false -out=tfplan -var="spn-client-id=$(tf-client-id)" -var="spn-client-secret=$(tf-client-secret)" -var="spn-tenant-id=$(tf-tenant-id)"
      workingDirectory: BattleShip_Site/build/terraform
  - task: ArchiveFiles@2
    displayName: Archive Terraform Plan Files
    inputs:
      rootFolderOrFile: BattleShip_Site/build/terraform
      archiveType: tar
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
  - task: PublishPipelineArtifact@1
    displayName: Publish Terraform Plan Artifact
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
      artifactName: $(Build.BuildId)-tfplan
...
